# Generated by Django 2.2 on 2019-04-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Schedule', to_field='date'),
        ),
    ]
